if has('gui')
  if has("gui_macvim")

    " xxxxxx Required for Closer.vim()
    " Found a better way that doesnt require mapping this!
    " " macmenu &File.Close key=<nop>

    macmenu &File.New\ Window key=<nop>
    macmenu &File.New\ Tab key=<nop>
    macmenu &File.New\ Tab key=<D-n>
    macmenu &File.New\ Window key=<D-N>
    macmenu &Tools.List\ Errors key=<nop>

    " Clear this up for something like CMD+t
    macmenu &File.Open\ Tab\.\.\. key=<nop>

    macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-c-f>
    macmenu &Tools.Make key=<nop>


    " From subvim:
    " Disable print shortcut for 'goto anything...'
    macmenu File.Print key=<nop>
  endif
endif

if filereadable(expand("~/.vim/gvimrc.local"))
  source ~/.vim/gvimrc.local
endif
