set nocompatible            " no compatibility with legacy vi

syntax enable               " enable syntax highlighting
set encoding=utf-8
set showcmd                 " display incomplete commands
filetype plugin indent on   " load file type plugins + indentation

"" set out tab characters, trailing whitespace and invisible spaces visually;
"" use the # sign at the end of lines to mark lines that extend off-screen.
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.
hi SpecialKey guifg=red
hi NonText guifg=orange

"" Whitespace
" set nowrap                      " don't wrap lines
set tabstop=4 shiftwidth=4      " a tab is four spaces
set shiftround
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode


"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

"" Filename autocompletion
set wildmenu
set wildmode=longest,list

"" Pathogen plugin manager - load plugins installed under ~/.vim/bundle
call pathogen#infect()


set splitbelow
set splitright

set hidden
set autochdir

" show line numbers
set number

" indent when moving to the next line
set autoindent

" show the matching part of the pair for [] {} and ()
set showmatch

"" change <leader> from '\' to ','
let mapleader=","

"" ,, to switch between two last buffers
nnoremap <Leader><Leader> <c-^>

"" <j><k> quickly is equivalent to ESC
inoremap jk <ESC>

"" quickly edit .vimrc
nmap <silent> <Leader>ev :e $MYVIMRC<CR>

"" quickly edit .vim/vim_crib.txt
nmap <silent> <Leader>ec :e $HOME/.vim/vim_crib.txt<CR>



" --- C/C++/Java ---------------------------------------------------------------
" my default C indentation options
set cinoptions=N-s,:0,l1,b1,g0,(0
set cinkeys=0=break

" --- PYTHON -------------------------------------------------------------------
" enable all Python syntax highlighting features
let python_highlight_all = 1
